/*
* Generated file
*
* Generated from: yang module name: apic-provider-impl yang module local name: apic-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jun 24 15:06:29 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.apic_provider.impl;
public class ApicProviderModuleFactory extends org.opendaylight.controller.config.yang.config.apic_provider.impl.AbstractApicProviderModuleFactory {

}
